apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  template:
    spec:
      containers:
      - image: us-docker.pkg.dev/davec-op-project/gcr.io/app:0.1.3
        env:
          - name: ENV
            value: prod
